### PR TITLE
reusable/installable package

### PR DESCRIPTION
**Pull request by wrboyce**
This PR aims to allow this library to be installed via `pip`/`easy_install` and exposes the functionality of `parse-ingredients.py` and `convert-to-json.py` as part of said library.

### CODE REVIEW

**Comment by adammck** [comment]
Thanks for the patch! This layout is definitely more conventional. But I don't understand why anyone would want to pip install this thing. Can you give me some context? What's your use-case?

**Comment by wrboyce** [comment]
I decided to download/index [BBC Food](https://www.bbc.co.uk/food) after the recent noises that we might lose it (which it now seems are unsubstantiated). Using this tagger seems to be the obvious choice to enhance the data I'd scraped. These recipes are very much UK centric so some new training was required, but I still ended up using a lot of the functionality in this repo. Most notable the import/export functions I refactored from the scripts, and `parseNumbers`/`cleanUnicodeFractions`.

**Comment by wrboyce** [comment]
Oh, and also this allowed me to run the code through `2to3`; the project I was using it from was using Python 3.

**Comment by adammck** [comment]
Sorry about the delay getting back to you on this. Works for me, and looks much better. Thank you!

**Pull request merged**
